### ISSUE TITLE
methratio.py -t end repair option does not work

### ISSUE THREAD

**Issue by tAndreani** [zyndagj/BSMAPz#10]
Hello,

am trying to extract the methylated cytosines. The program works perfectly but if I want to use the end repair option (-t or "--trim-fillin") it fails. This is the output:
```
Traceback (most recent call last):
  File "/data/SHARED_SOFTWARE/anaconda3/envs/scMeth/bin/methratio.py", line 571, in <module>
    main()
  File "/data/SHARED_SOFTWARE/anaconda3/envs/scMeth/bin/methratio.py", line 138, in main
    ret = map(chromWorker, argList)
  File "/data/SHARED_SOFTWARE/anaconda3/envs/scMeth/bin/methratio.py", line 283, in chromWorker
    refseq = refCache.fetch(pos, pos2)
  File "/data/SHARED_SOFTWARE/anaconda3/envs/scMeth/bin/methratio.py", line 214, in fetch
    assert(pos >= self.start)
AssertionError
``` 

I am using python-2.7.3

Any suggestions?
Thanks in advance,
Tommaso

**Comment by zyndagj** [comment]
Hello,

That option shouldn't affect the sequence cache, but I'll try to reproduce and get back to you.

-Greg

**Comment by tAndreani** [comment]
Thanks, Greg, let me know if you need the bam file I have used as input. Is not that big because is from a single cell.

Best
Tommaso

**Comment by zyndagj** [comment]
I updated the reference cache in version 1.1.2, which should resolve your issue. Please pull it from github or conda and let me know how it goes.
