### ISSUE TITLE
methratio exception

### ISSUE THREAD

**Issue by eitanmarcus** [zyndagj/BSMAPz#28]
I recently updated to bsmapz (from an older version of bsmap) and consistently been getting the following error:

methratio] @Tue Jul 14 15:37:26 2020 	chr3 used 127582 reads
[methratio] @Tue Jul 14 15:37:26 2020 	combining CpG methylation from both strands of chr3...
Traceback (most recent call last):
  File "/usr/local/bioinfo/bsmapz/1.1.2/bin/methratio.py", line 585, in <module>
    main()
  File "/usr/local/bioinfo/bsmapz/1.1.2/bin/methratio.py", line 138, in main
    ret = chromPool.map(chromWorker, argList, chunksize=1)
  File "/usr/local/bioinfo/bioconda/envs/samtools/lib/python2.7/multiprocessing/pool.py", line 253, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/usr/local/bioinfo/bioconda/envs/samtools/lib/python2.7/multiprocessing/pool.py", line 572, in get
    raise self._value
UnboundLocalError: local variable 'depth1' referenced before assignment

This occurs after all the chromosomes have been read.

The command line I am running is :
methratio.py -g -z -x CG -i no-action -I -p -u -d mm10/Sequence/WholeGenomeFasta/genome.fa Run3_C4_MyoD_B_2.bam

**Comment by zyndagj** [comment]
Hello,

Thanks for submitting the error, and sorry for any frustration. I have moved to automated testing, but they they don't cover all combinations of arguments yet. I'm going to try replicating your issue with my test data and I'll get back to you.

**Comment by eitanmarcus** [comment]
Greg
If it would be helpful I can share with you the input bam file.

**Comment by zyndagj** [comment]
Assuming the file is large, you can share it with `gzynda` on [CyVerse](https://de.cyverse.org), or I can download it from a public repo you can upload to.

**Comment by eitanmarcus** [comment]
Greg
First I apologize for the delayed response, unfortunately our system has
done a major upgrade and many things stopped working.

You can access a sample bam file here
<https://www.cs.huji.ac.il/~ofra.sabag/?dir=Zynda>.Please let me know if
you have any problems accessing it. I don't believe there is anything
special about the bam file. It was created by:
bsmapz -S 10 -R -p 8 -D C-CGG -a Cerebellum_R1_val_1.fq.gz -b
Cerebellum_R2_val_2.fq.gz -d genome.fa -o Cerebellum.sam
samtools view -b -S Cerebellum.sam | samtools sort -o Cerebellum.bam

One thing I noticed is that methratio is using Python 2.7.15. This is
because the first line in the script is:
#! /usr/bin/env python
which doesnt exist on our system (and our default python is 2.7.15). I
tried redirecting it to version Python 3.7.6, but that caused other
problems.

Howard

**Comment by eitanmarcus** [comment]
Greg
Were you able to reproduce this problem? It may be that my environment is not set up correctly since we recently updated our system. The problem may be in that bsmapz/methratio.py have many dependencies (python, samtools, etc.) and  my environment is not correct.

Howard

**Comment by zyndagj** [comment]
Howard,

I was able to reproduce your problem, and will finish up a patch this week.

```
$ methratio.py -g -z -x CG -i no-action -I -p -u -d mm10.fa Cerebellum.bam
[methratio] @Wed Aug  5 16:54:33 2020   Missing output file name, write to STDOUT.
[methratio] @Wed Aug  5 16:54:33 2020   Using 90% of available memory (36318 MB) as limit
chr     pos     strand  context ratio   eff_CT_count    C_count CT_count        rev_G_count     rev_GA_count    CI_lower        CI_upper
[methratio] @Wed Aug  5 16:54:33 2020   Presorting inputs
[methratio] @Wed Aug  5 16:54:33 2020   Calling samtools sort on Cerebellum.bam and using 1297 MB of memory
[bam_sort_core] merging from 0 files and 28 in-memory blocks...
[methratio] @Wed Aug  5 16:54:34 2020   Processing 11 chromosomes at a time
[methratio] @Wed Aug  5 16:54:36 2020   Reading chr19 from Cerebellum.tmpSrt.bam with samtools
[methratio] @Wed Aug  5 16:54:36 2020   chr19 used 1508 reads
[methratio] @Wed Aug  5 16:54:36 2020   combining CpG methylation from both strands of chr19...
[methratio] @Wed Aug  5 16:54:36 2020   Reading chr18 from Cerebellum.tmpSrt.bam with samtools
[methratio] @Wed Aug  5 16:54:36 2020   Reading chr17 from Cerebellum.tmpSrt.bam with samtools
[methratio] @Wed Aug  5 16:54:36 2020   Reading chr16 from Cerebellum.tmpSrt.bam with samtools
[methratio] @Wed Aug  5 16:54:36 2020   chr18 used 132 reads
[methratio] @Wed Aug  5 16:54:36 2020   combining CpG methylation from both strands of chr18...
[methratio] @Wed Aug  5 16:54:36 2020   chr17 used 68 reads
[methratio] @Wed Aug  5 16:54:36 2020   combining CpG methylation from both strands of chr17...
[methratio] @Wed Aug  5 16:54:36 2020   chr16 used 216 reads
[methratio] @Wed Aug  5 16:54:36 2020   combining CpG methylation from both strands of chr16...
[methratio] @Wed Aug  5 16:54:36 2020   Reading chr15 from Cerebellum.tmpSrt.bam with samtools
[methratio] @Wed Aug  5 16:54:36 2020   chr15 used 2110 reads
[methratio] @Wed Aug  5 16:54:36 2020   combining CpG methylation from both strands of chr15...
[methratio] @Wed Aug  5 16:54:37 2020   Reading chr13 from Cerebellum.tmpSrt.bam with samtools
[methratio] @Wed Aug  5 16:54:37 2020   Reading chr12 from Cerebellum.tmpSrt.bam with samtools
[methratio] @Wed Aug  5 16:54:37 2020   Reading chr11 from Cerebellum.tmpSrt.bam with samtools
[methratio] @Wed Aug  5 16:54:37 2020   Reading chr14 from Cerebellum.tmpSrt.bam with samtools
[methratio] @Wed Aug  5 16:54:37 2020   chr13 used 1066 reads
[methratio] @Wed Aug  5 16:54:37 2020   combining CpG methylation from both strands of chr13...
[methratio] @Wed Aug  5 16:54:37 2020   Reading chr10 from Cerebellum.tmpSrt.bam with samtools
[methratio] @Wed Aug  5 16:54:37 2020   chr12 used 616 reads
[methratio] @Wed Aug  5 16:54:37 2020   combining CpG methylation from both strands of chr12...
[methratio] @Wed Aug  5 16:54:37 2020   chr11 used 316 reads
[methratio] @Wed Aug  5 16:54:37 2020   combining CpG methylation from both strands of chr11...
[methratio] @Wed Aug  5 16:54:37 2020   chr14 used 80 reads
[methratio] @Wed Aug  5 16:54:37 2020   combining CpG methylation from both strands of chr14...
[methratio] @Wed Aug  5 16:54:37 2020   chr10 used 116 reads
[methratio] @Wed Aug  5 16:54:37 2020   combining CpG methylation from both strands of chr10...
[methratio] @Wed Aug  5 16:54:38 2020   Reading chr1 from Cerebellum.tmpSrt.bam with samtools
[methratio] @Wed Aug  5 16:54:38 2020   chr1 used 420 reads
[methratio] @Wed Aug  5 16:54:38 2020   combining CpG methylation from both strands of chr1...
Traceback (most recent call last):
  File "./methratio.py", line 585, in <module>
    main()
  File "./methratio.py", line 138, in main
    ret = chromPool.map(chromWorker, argList, chunksize=1)
  File "/opt/apps/intel18/python2/2.7.15/lib/python2.7/multiprocessing/pool.py", line 253, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/opt/apps/intel18/python2/2.7.15/lib/python2.7/multiprocessing/pool.py", line 572, in get
    raise self._value
UnboundLocalError: local variable 'depth1' referenced before assignment
```

Thanks again for posting your input file.

**Comment by zyndagj** [comment]
I created tests each of your arguments, and found that `-i no-action` triggers it.

Test case
```
python methratio.py -i no-action -z -r -d $(REF) -o $@ $< &> $@.log || { cat $@.log; exit 1; }
```

```
$ make test
[methratio] @Sat Aug  8 12:03:44 2020   Using 90% of available memory (40795 MB) as limit
[methratio] @Sat Aug  8 12:03:44 2020   Presorting inputs
[methratio] @Sat Aug  8 12:03:44 2020   Calling samtools sort on test_data/test_paired.bam and using 1456 MB of memory
[bam_sort_core] merging from 0 files and 28 in-memory blocks...
[methratio] @Sat Aug  8 12:03:45 2020   Processing 2 chromosomes at a time
[methratio] @Sat Aug  8 12:03:45 2020   Reading chr2 from test_data/test_paired.tmpSrt.bam with samtools
[methratio] @Sat Aug  8 12:03:45 2020   Reading chr1 from test_data/test_paired.tmpSrt.bam with samtools
[methratio] @Sat Aug  8 12:03:45 2020   chr2 used 1637 reads
[methratio] @Sat Aug  8 12:03:45 2020   chr1 used 1660 reads
[methratio] @Sat Aug  8 12:03:45 2020   writing chr1 to test_data/test_paired_ct.bam.mr ...
Traceback (most recent call last):
  File "methratio.py", line 585, in <module>
    main()
  File "methratio.py", line 138, in main
    ret = chromPool.map(chromWorker, argList, chunksize=1)
  File "/opt/apps/intel18/python2/2.7.15/lib/python2.7/multiprocessing/pool.py", line 253, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/opt/apps/intel18/python2/2.7.15/lib/python2.7/multiprocessing/pool.py", line 572, in get
    raise self._value
UnboundLocalError: local variable 'depth1' referenced before assignment
make: *** [test_data/test_paired_ct.bam.mr] Error 1
```

I'll be including all these tests in my CI from now on.

**Comment by zyndagj** [comment]
The release build of v1.1.3 just started, but it should fix your error.

https://github.com/zyndagj/BSMAPz/releases/tag/1.1.3

Let me know if you have any issues.

-Greg
