### ISSUE TITLE
methdiff.py error

### ISSUE THREAD

**Issue by Albacc15** [zyndagj/BSMAPz#39]
Hello!
I am learning the bisulfite pipeline, but when I get into methdiff.py it retrieves an index error: array index out of range
This is the code:

`python2 /home/alba/SOFTWARE/BSMAPz/methdiff.py -d Mus_musculus.GRCm39.dna.primary_assembly.fa -p 0.05 -b 10 -l WT,KO WT_1L,WT_2L,WT_3L KO_1L,KO_2L,KO_3L -o OUTPUT.txt`

It seems to work but ends up with the error and the output is a txt with the headers but empty. This is what it retrieves:

[methdiff] @Thu Dec  2 14:21:09 2021 	reading reference file: Mus_musculus.GRCm39.dna.primary_assembly.fa ...
[methdiff] @Thu Dec  2 14:21:22 2021 	processing 1 dna:chromosome chromosome:GRCm39:1:1:195154279:1 REF ...
[methdiff] @Thu Dec  2 14:21:29 2021 	processing 10 dna:chromosome chromosome:GRCm39:10:1:130530862:1 REF ...
[methdiff] @Thu Dec  2 14:21:34 2021 	processing 11 dna:chromosome chromosome:GRCm39:11:1:121973369:1 REF ...
[methdiff] @Thu Dec  2 14:21:38 2021 	processing 12 dna:chromosome chromosome:GRCm39:12:1:120092757:1 REF ...
[methdiff] @Thu Dec  2 14:21:43 2021 	processing 13 dna:chromosome chromosome:GRCm39:13:1:120883175:1 REF ...
[methdiff] @Thu Dec  2 14:21:47 2021 	processing 14 dna:chromosome chromosome:GRCm39:14:1:125139656:1 REF ...
[methdiff] @Thu Dec  2 14:21:52 2021 	processing 15 dna:chromosome chromosome:GRCm39:15:1:104073951:1 REF ...
[methdiff] @Thu Dec  2 14:21:56 2021 	processing 16 dna:chromosome chromosome:GRCm39:16:1:98008968:1 REF ...
[methdiff] @Thu Dec  2 14:22:00 2021 	processing 17 dna:chromosome chromosome:GRCm39:17:1:95294699:1 REF ...
[methdiff] @Thu Dec  2 14:22:03 2021 	processing 18 dna:chromosome chromosome:GRCm39:18:1:90720763:1 REF ...
[methdiff] @Thu Dec  2 14:22:07 2021 	processing 19 dna:chromosome chromosome:GRCm39:19:1:61420004:1 REF ...
[methdiff] @Thu Dec  2 14:22:09 2021 	processing 2 dna:chromosome chromosome:GRCm39:2:1:181755017:1 REF ...
[methdiff] @Thu Dec  2 14:22:16 2021 	processing 3 dna:chromosome chromosome:GRCm39:3:1:159745316:1 REF ...
[methdiff] @Thu Dec  2 14:22:22 2021 	processing 4 dna:chromosome chromosome:GRCm39:4:1:156860686:1 REF ...
[methdiff] @Thu Dec  2 14:22:28 2021 	processing 5 dna:chromosome chromosome:GRCm39:5:1:151758149:1 REF ...
[methdiff] @Thu Dec  2 14:22:34 2021 	processing 6 dna:chromosome chromosome:GRCm39:6:1:149588044:1 REF ...
[methdiff] @Thu Dec  2 14:22:39 2021 	processing 7 dna:chromosome chromosome:GRCm39:7:1:144995196:1 REF ...
[methdiff] @Thu Dec  2 14:22:45 2021 	processing 8 dna:chromosome chromosome:GRCm39:8:1:130127694:1 REF ...
[methdiff] @Thu Dec  2 14:22:50 2021 	processing 9 dna:chromosome chromosome:GRCm39:9:1:124359700:1 REF ...
Traceback (most recent call last):
  **File "/home/alba/SOFTWARE/BSMAPz/methdiff.py", line 135, in <module>
    cmp_chrom(cr)
  File "/home/alba/SOFTWARE/BSMAPz/methdiff.py", line 105, in cmp_chrom
    m[i] = meth[i][pos]
IndexError: array index out of range**

I would really appreciate if you could help me with this issue. Thank you in advance,

Alba

**Comment by Akshaygala** [comment]
I am facing the same issue. Did you get around this error?
