### ISSUE TITLE
methratio.py AssertionError

### ISSUE THREAD

**Issue by animaltracks7** [zyndagj/BSMAPz#42]
Hi, 
I'm getting an error when running methratio.py.
Code: methratio.py -o methratio.txt -d Genome.fna -r bsmap.bam
Output:
[methratio] @Sat Apr  9 20:12:26 2022   Using 90% of available memory (11165 MB) as limit
[methratio] @Sat Apr  9 20:12:26 2022   Presorting inputs
[methratio] @Sat Apr  9 20:12:26 2022   Processing 8 chromosomes at a time
Traceback (most recent call last):
  File "/usr/local/bin/methratio.py", line 590, in <module>
    main()
  File "/usr/local/bin/methratio.py", line 136, in main
    chromPool = ChromPool(maxChromProcs)
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 212, in __init__
    self._repopulate_pool()
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 303, in _repopulate_pool
    return self._repopulate_pool_static(self._ctx, self.Process,
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 319, in _repopulate_pool_static
    w = Process(ctx, target=worker,
  File "/usr/lib/python3.8/multiprocessing/process.py", line 82, in __init__
    assert group is None, 'group argument must be None for now'
AssertionError: group argument must be None for now

Any idea what is wrong? Thanks.

**Comment by shraddhapai** [comment]
Hi, I just ran into the same issue running `make test` on an Ubuntu 18.04 system. 
Were you able to resolve this? Thanks.

**Comment by Logancreator** [comment]
Hi, have u solved this problem? I have same error...

**Comment by shawarden** [comment]
Same issue here.

```
❯ make test
OK - Finished aligning test_data/test_paired.sam
OK - converted test_data/test_paired.sam to sorted and indexed BAM
[methratio] @Mon Apr  8 15:47:36 2024   Using 90% of available memory (2476 MB) as limit
[methratio] @Mon Apr  8 15:47:36 2024   Presorting inputs
[methratio] @Mon Apr  8 15:47:36 2024   Processing 2 chromosomes at a time
Traceback (most recent call last):
File "/resource/apps/BSMAPz/methratio.py", line 590, in <module>
main()
File "/resource/apps/BSMAPz/methratio.py", line 136, in main
chromPool = ChromPool(maxChromProcs)
File "/resource/easybuild/software/Python/3.10.8-GCCcore-12.2.0/lib/python3.10/multiprocessing/pool.py", line 215, in __init__
self._repopulate_pool()
File "/resource/easybuild/software/Python/3.10.8-GCCcore-12.2.0/lib/python3.10/multiprocessing/pool.py", line 306, in _repopulate_pool
return self._repopulate_pool_static(self._ctx, self.Process,
File "/resource/easybuild/software/Python/3.10.8-GCCcore-12.2.0/lib/python3.10/multiprocessing/pool.py", line 322, in _repopulate_pool_static
w = Process(ctx, target=worker,
File "/resource/easybuild/software/Python/3.10.8-GCCcore-12.2.0/lib/python3.10/multiprocessing/process.py", line 82, in __init__
assert group is None, 'group argument must be None for now'
AssertionError: group argument must be None for now
make: *** [Makefile:70: test_data/test_paired.sam.bam.mr] Error 1
```
